### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by abryrath** [simonhamp/tableplus-phpserializer#1]
Hello, I am having trouble getting this plugin to work as described. I see the option 'PHP Deserialize' when I right-click a cell, but then nothing is coped to my clipboard.

Is there an error log where I can see what is happening or any possible errors?

System details:
MacOS Catalina 10.15.2
TablePlus Version 2.12 (282)
Using plugin Release 0.1.0 from Github Releases (not built from source)

**Comment by simonhamp** [comment]
Thanks for trying out the plugin and taking the time to report your issue.

Can I just double-check that you’re right-clicking _on the cell with serialized data_? This is important as there’s currently no other way to define the source to be deserialized.

If you are clicking on the correct cell, would it be possible to share the serialized data from that cell here so that I can test on my side?

**Comment by abryrath** [comment]
Yes, I am right-clicking a cell with serialized data; I would not expect it to deserialize unserialized data.

Here is a text block of the serialized data. Note that it is using a serialized object. Does this plugin only work with primitive data types?

```
O:42:"craft\queue\jobs\UpdateElementSlugsAndUris":10:{s:9:"elementId";i:103794;s:11:"elementType";s:20:"craft\elements\Entry";s:6:"siteId";s:1:"1";s:16:"updateOtherSites";b:1;s:17:"updateDescendants";b:1;s:59:"craft\queue\jobs\UpdateElementSlugsAndUris_totalToProcess";N;s:59:"craft\queue\jobs\UpdateElementSlugsAndUris_totalProcessed";N;s:11:"description";N;s:30:"craft\queue\BaseJob_progress";i:0;s:35:"craft\queue\BaseJob_progressLabel";N;}
```

**Comment by simonhamp** [comment]
@abryrath unfortunately this string doesn't contain the zero-space binary characters that normally separate the various elements of a PHP serialized string. Could you possibly dump the serialized string to a file and send that instead?
